using NUnit.Framework;
using Xamarin.Forms;

namespace XAMLator.Server.Tests
{
	[TestFixture]
	public class XAMLEvaluationFeature : XAMLatorFeatureBase
	{

		[Test]
		public void A_xaml_changes_and_the_view_is_previewed()
		{
			When_a_xaml_document_changes("TestPage.xaml");
			Assert.AreEqual(PreviewState.Preview, previewer.State);
			Assert.AreEqual("XAMLator.Server.Tests.TestPage", previewer.EvalResult.ResultType.FullName);
		}

		[Test]
		public void When_a_xaml_element_name_is_changed_the_code_behind_is_autogenerated()
		{
			When_a_xaml_document_changes("TestPage.xaml",
				@"<?xml version=""1.0"" encoding=""UTF-8""?>
				<ContentPage xmlns=""http://xamarin.com/schemas/2014/forms""
						    xmlns:x=""http://schemas.microsoft.com/winfx/2009/xaml""
						    x:Class=""XAMLator.Server.Tests.TestPage"">
    					<ContentPage.Content>
        					<Label x:Name=""newLabel"" Text=""Sample""/>
    					</ContentPage.Content>
				</ContentPage>
			".Trim());

			var contentPage = previewer.PreviewedPage as ContentPage;

			Assert.AreEqual(PreviewState.Preview, previewer.State);
			Assert.AreEqual("Sample", contentPage.FindByName<Label>("newLabel").Text);
		}

		[Test]
		public void When_a_xaml_changes_the_previwed_view_has_the_new_changes()
		{
			When_a_xaml_document_changes("TestPage.xaml",
				@"<?xml version=""1.0"" encoding=""UTF-8""?>
				<ContentPage xmlns=""http://xamarin.com/schemas/2014/forms""
						    xmlns:x=""http://schemas.microsoft.com/winfx/2009/xaml""
						    x:Class=""XAMLator.Server.Tests.TestPage"">
    					<ContentPage.Content>
        					<Label x:Name=""newLabel"" Text=""New text""/>
    					</ContentPage.Content>
				</ContentPage>
			".Trim());
			var contentPage = previewer.PreviewedPage as ContentPage;

			Assert.AreEqual(PreviewState.Preview, previewer.State);
			Assert.AreEqual("New text", (contentPage.Content as Label).Text);
		}

		[Test]
		public void When_the_xaml_contains_a_sytax_error_the_error_page_is_shown()
		{
			When_a_xaml_document_changes("TestPage.xaml", @"
				<?xml version=""1.0"" encoding=""UTF-8""?>
				<ContentPage".Trim());
			Assert.AreEqual(PreviewState.Error, previewer.State);
		}

		[Test]
		public void When_the_xaml_contains_an_error_the_error_page_is_shown()
		{
			When_a_xaml_document_changes("TestPage.xaml",
				@"<?xml version=""1.0"" encoding=""UTF-8""?>
				<ContentPage xmlns=""http://xamarin.com/schemas/2014/forms""
						    xmlns:x=""http://schemas.microsoft.com/winfx/2009/xaml""
						    x:Class=""XAMLator.Server.Tests.TestPage"">
    					<ContentPage.Cotent>
        					<Label x:Name=""newLabel"" Text=""Sample""/>
    					</ContentPage.Cotent>
				</ContentPage>
			".Trim());
			Assert.AreEqual(PreviewState.Error, previewer.State);
		}
	}
}